workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_LIBRARY_FOR_DISTRIBUTION: "NO"
    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get

      - name: Pod clean & install
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS simulator app
        script: |
          flutter build ios --simulator --no-codesign

      - name: Package app
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app

    artifacts:
      - build/ios/ipa/Runner.app.zip
