workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUILD_LIBRARY_FOR_DISTRIBUTION: "NO"
    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get

      - name: Pod install
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS device app
        script: |
          flutter build ios --release

    artifacts:
      - build/ios/iphoneos/Runner.app
