platform :ios, '12.0'

flutter_sdk_path = ENV['FLUTTER_ROOT']
load File.join(flutter_sdk_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)
end
