platform :ios, '12.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Use the Flutter SDK path from environment (Codemagic sets this automatically)
flutter_sdk_path = ENV['FLUTTER_ROOT']
load File.join(flutter_sdk_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['DEFINES_MODULE'] = 'NO'
      config.build_settings['SWIFT_ENABLE_LIBRARY_EVOLUTION'] = 'NO'
      config.build_settings['OTHER_SWIFT_FLAGS'] = ''
    end
  end
end
